#!/bin/sh
# shellguard-configure — interactive Telegram setup and service start
# Usage: shellguard-configure [--start] [--test-only]
set -e

CONF="/etc/shellguard/shellguard.conf"
CONF_EXAMPLE="/etc/shellguard/shellguard.conf.example"
RC_SRC="/usr/lib/shellguard/synology-rc"
RC_DST="/usr/local/etc/rc.d/S99shellguard"
GITHUB_REPO="merabytes/shellguard"

DO_START=0
TEST_ONLY=0

for arg in "$@"; do
    case "$arg" in
        --start)     DO_START=1 ;;
        --test-only) TEST_ONLY=1 ;;
    esac
done

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "Run as root: sudo $0" >&2
        exit 1
    fi
}

is_synology() {
    [ -f /etc/synoinfo.conf ] || [ -d /usr/syno ]
}

read_secret_tty() {
    _prompt=$1
    _val=""
    if [ ! -r /dev/tty ]; then
        echo "Need a TTY or set SHELLGUARD_TG_TOKEN in the environment." >&2
        exit 1
    fi
    printf '%s' "$_prompt" >/dev/tty
    IFS= read -r -s _val </dev/tty
    printf '\n' >/dev/tty
    printf '%s' "$_val"
}

read_line_tty() {
    _prompt=$1
    _val=""
    if [ ! -r /dev/tty ]; then
        echo "Need a TTY or set the value in the environment." >&2
        exit 1
    fi
    printf '%s' "$_prompt" >/dev/tty
    IFS= read -r _val </dev/tty
    printf '%s' "$_val"
}

prompt_telegram() {
    echo ""
    echo "=== ShellGuard — Telegram setup ==="
    echo "Create a bot with @BotFather (/newbot) and add it to your chat/channel."
    echo "For forum topics: enable Topics in the group, then open the topic and copy its ID."
    echo ""

    if [ -z "${SHELLGUARD_TG_TOKEN:-}" ]; then
        SHELLGUARD_TG_TOKEN=$(read_secret_tty "Telegram bot token: ")
    fi
    if [ -z "${SHELLGUARD_TG_CHAT:-}" ]; then
        SHELLGUARD_TG_CHAT=$(read_line_tty "Telegram chat ID (e.g. -1001234567890): ")
    fi
    if [ -z "${SHELLGUARD_TG_TOPIC+x}" ]; then
        if [ -r /dev/tty ]; then
            SHELLGUARD_TG_TOPIC=$(read_line_tty "Forum topic ID (optional, Enter to skip): ")
        else
            SHELLGUARD_TG_TOPIC=""
        fi
    fi

    if [ -z "${SHELLGUARD_TG_TOKEN:-}" ] || [ -z "${SHELLGUARD_TG_CHAT:-}" ]; then
        echo "Bot token and chat ID are required." >&2
        exit 1
    fi
}

write_config() {
    mkdir -p /etc/shellguard
    _host=""
    if [ -f "$CONF" ]; then
        _host=$(grep '^SHELLGUARD_HOST=' "$CONF" 2>/dev/null | cut -d= -f2- | tr -d '"')
    fi

    {
        printf '%s\n' "# ShellGuard — generated by shellguard-configure"
        printf '%s\n' "SHELLGUARD_HOST=${_host:-}"
        printf '%s\n' "POLL_INTERVAL=2"
        printf '%s\n' "DEDUP_WINDOW=60"
        printf '%s\n' "LOG_FILE=/var/log/shellguard.log"
        printf '%s\n' "LOG_STDOUT=1"
        printf '%s\n' ""
        printf '%s\n' "TELEGRAM_ENABLED=1"
        printf 'TELEGRAM_BOT_TOKEN=%s\n' "$SHELLGUARD_TG_TOKEN"
        printf 'TELEGRAM_CHAT_ID=%s\n' "$SHELLGUARD_TG_CHAT"
        if [ -n "${SHELLGUARD_TG_TOPIC:-}" ]; then
            printf 'TELEGRAM_TOPIC_ID=%s\n' "$SHELLGUARD_TG_TOPIC"
        else
            printf '%s\n' 'TELEGRAM_TOPIC_ID='
        fi
        printf '%s\n' ""
        printf '%s\n' "SLACK_ENABLED=0"
        printf '%s\n' "SLACK_WEBHOOK_URL="
        printf '%s\n' ""
        printf '%s\n' "WEBHOOK_ENABLED=0"
        printf '%s\n' "WEBHOOK_URL="
        printf '%s\n' "WEBHOOK_SECRET="
    } > "$CONF"

    chmod 600 "$CONF"
    echo "Wrote $CONF (mode 600)"
}

test_telegram() {
    _host=$(hostname 2>/dev/null || echo "shellguard")
    _msg="[ShellGuard] Test alert from ${_host}
If you see this, Telegram is configured correctly."
    _url="https://api.telegram.org/bot${SHELLGUARD_TG_TOKEN}/sendMessage"

    echo "Sending test message to Telegram..."
    if [ -n "${SHELLGUARD_TG_TOPIC:-}" ]; then
        _resp=$(curl -s --max-time 15 "$_url" \
            --data-urlencode "chat_id=${SHELLGUARD_TG_CHAT}" \
            --data-urlencode "text=${_msg}" \
            --data-urlencode "message_thread_id=${SHELLGUARD_TG_TOPIC}" \
            2>/dev/null) || _resp=""
    else
        _resp=$(curl -s --max-time 15 "$_url" \
            --data-urlencode "chat_id=${SHELLGUARD_TG_CHAT}" \
            --data-urlencode "text=${_msg}" \
            2>/dev/null) || _resp=""
    fi

    if printf '%s' "$_resp" | grep -q '"ok"[[:space:]]*:[[:space:]]*true'; then
        echo "Telegram test OK."
        return 0
    fi

    _err=$(printf '%s' "$_resp" | grep -o '"description":"[^"]*"' | head -1 | sed 's/"description":"//;s/"$//')
    echo "Telegram test failed.${_err:+ $_err}" >&2
    [ -n "$_resp" ] && echo "API response: $_resp" >&2
    exit 1
}

setup_synology_service() {
    [ -f "$RC_SRC" ] || return 0
    mkdir -p "$(dirname "$RC_DST")"
    cp "$RC_SRC" "$RC_DST"
    chmod 755 "$RC_DST"
    echo "Installed boot script: $RC_DST"
}

start_service() {
    if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
        systemctl daemon-reload 2>/dev/null || true
        systemctl enable shellguard.service 2>/dev/null || true
        systemctl restart shellguard.service
        systemctl --no-pager status shellguard.service || true
        return
    fi

    if is_synology || [ ! -x /usr/bin/systemctl ]; then
        setup_synology_service
        if [ -x "$RC_DST" ]; then
            "$RC_DST" restart
            "$RC_DST" status || true
        else
            echo "Start manually: /usr/bin/shellguard -c $CONF &"
        fi
        return
    fi

    echo "Start manually: /usr/bin/shellguard -c $CONF &"
}

require_root

if [ ! -f "$CONF_EXAMPLE" ] && [ ! -f /usr/bin/shellguard ]; then
    echo "ShellGuard is not installed. Run scripts/install-synology.sh first." >&2
    exit 1
fi

prompt_telegram

if [ "$TEST_ONLY" = "1" ]; then
    test_telegram
    exit 0
fi

write_config
test_telegram

if [ "$DO_START" = "1" ]; then
    start_service
    echo ""
    echo "ShellGuard is running. Open a new shell to trigger an alert."
    echo "Logs: tail -f /var/log/shellguard.log"
    echo "Reconfigure anytime: shellguard-configure --start"
fi
