#!/bin/sh
# shellguard-configure — interactive Telegram setup and service start
# Usage: shellguard-configure [--start] [--test-only] [--verbose]
# Env:   SHELLGUARD_VERBOSE=1  SHELLGUARD_TG_TOKEN  SHELLGUARD_TG_CHAT  SHELLGUARD_TG_TOPIC
set -e

CONFIGURE_VERSION="2"
CONF="/etc/shellguard/shellguard.conf"
CONF_EXAMPLE="/etc/shellguard/shellguard.conf.example"
RC_SRC="/usr/lib/shellguard/synology-rc"
RC_DST="/usr/local/etc/rc.d/S99shellguard"

DO_START=0
TEST_ONLY=0
VERBOSE=0

for arg in "$@"; do
    case "$arg" in
        --start)     DO_START=1 ;;
        --test-only) TEST_ONLY=1 ;;
        --verbose|-v) VERBOSE=1 ;;
    esac
done

[ "${SHELLGUARD_VERBOSE:-0}" = "1" ] && VERBOSE=1

vlog() {
    [ "$VERBOSE" = "1" ] && printf '[verbose] %s\n' "$*" >&2
}

mask_secret() {
    _s=$1
    _n=$(printf '%s' "$_s" | wc -c | tr -d ' ')
    if [ "$_n" -le 6 ]; then
        printf '***'
        return
    fi
    _start=$(printf '%s' "$_s" | cut -c1-4)
    _end=$(printf '%s' "$_s" | tail -c 4)
    printf '%s...%s' "$_start" "$_end"
}

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "Run as root: sudo $0" >&2
        exit 1
    fi
}

is_synology() {
    [ -f /etc/synoinfo.conf ] || [ -d /usr/syno ]
}

read_secret_tty() {
    _prompt=$1
    _val=""
    if [ ! -r /dev/tty ]; then
        echo "Need a TTY or set SHELLGUARD_TG_TOKEN in the environment." >&2
        exit 1
    fi
    printf '%s' "$_prompt" >/dev/tty
    IFS= read -r -s _val </dev/tty
    printf '\n' >/dev/tty
    printf '%s' "$_val"
}

read_line_tty() {
    _prompt=$1
    _val=""
    if [ ! -r /dev/tty ]; then
        echo "Need a TTY or set the value in the environment." >&2
        exit 1
    fi
    printf '%s' "$_prompt" >/dev/tty
    IFS= read -r _val </dev/tty
    printf '%s' "$_val"
}

prompt_telegram() {
    echo ""
    echo "=== ShellGuard — Telegram setup (configure v${CONFIGURE_VERSION}) ==="
    echo "Create a bot with @BotFather (/newbot) and add it to your chat/channel."
    echo "For forum topics: enable Topics in the group, then open the topic and copy its ID."
    echo "Verbose: shellguard-configure --verbose   or   SHELLGUARD_VERBOSE=1"
    echo ""

    if [ -z "${SHELLGUARD_TG_TOKEN:-}" ]; then
        SHELLGUARD_TG_TOKEN=$(read_secret_tty "Telegram bot token: ")
    fi
    if [ -z "${SHELLGUARD_TG_CHAT:-}" ]; then
        SHELLGUARD_TG_CHAT=$(read_line_tty "Telegram chat ID (e.g. -1001234567890): ")
    fi
    if [ -z "${SHELLGUARD_TG_TOPIC+x}" ]; then
        if [ -r /dev/tty ]; then
            SHELLGUARD_TG_TOPIC=$(read_line_tty "Forum topic ID (optional, Enter to skip): ")
        else
            SHELLGUARD_TG_TOPIC=""
        fi
    fi

    if [ -z "${SHELLGUARD_TG_TOKEN:-}" ] || [ -z "${SHELLGUARD_TG_CHAT:-}" ]; then
        echo "Bot token and chat ID are required." >&2
        exit 1
    fi

    vlog "token=$(mask_secret "$SHELLGUARD_TG_TOKEN") len=$(printf '%s' "$SHELLGUARD_TG_TOKEN" | wc -c | tr -d ' ')"
    vlog "chat_id=${SHELLGUARD_TG_CHAT}"
    vlog "topic_id=${SHELLGUARD_TG_TOPIC:-<empty>}"
}

write_config() {
    mkdir -p /etc/shellguard
    _host=""
    if [ -f "$CONF" ]; then
        _host=$(grep '^SHELLGUARD_HOST=' "$CONF" 2>/dev/null | cut -d= -f2- | tr -d '"')
    fi

    {
        printf '%s\n' "# ShellGuard — generated by shellguard-configure"
        printf '%s\n' "SHELLGUARD_HOST=${_host:-}"
        printf '%s\n' "POLL_INTERVAL=2"
        printf '%s\n' "DEDUP_WINDOW=60"
        printf '%s\n' "LOG_FILE=/var/log/shellguard.log"
        printf '%s\n' "LOG_STDOUT=1"
        printf '%s\n' ""
        printf '%s\n' "TELEGRAM_ENABLED=1"
        printf 'TELEGRAM_BOT_TOKEN=%s\n' "$SHELLGUARD_TG_TOKEN"
        printf 'TELEGRAM_CHAT_ID=%s\n' "$SHELLGUARD_TG_CHAT"
        if [ -n "${SHELLGUARD_TG_TOPIC:-}" ]; then
            printf 'TELEGRAM_TOPIC_ID=%s\n' "$SHELLGUARD_TG_TOPIC"
        else
            printf '%s\n' 'TELEGRAM_TOPIC_ID='
        fi
        printf '%s\n' ""
        printf '%s\n' "SLACK_ENABLED=0"
        printf '%s\n' "SLACK_WEBHOOK_URL="
        printf '%s\n' ""
        printf '%s\n' "WEBHOOK_ENABLED=0"
        printf '%s\n' "WEBHOOK_URL="
        printf '%s\n' "WEBHOOK_SECRET="
    } > "$CONF"

    chmod 600 "$CONF"
    echo "Wrote $CONF (mode 600)"
    vlog "config written to $CONF"
}

telegram_api() {
    _method=$1
    shift
    _base="https://api.telegram.org/bot${SHELLGUARD_TG_TOKEN}/${_method}"
    _out="/tmp/shellguard_tg_resp.$$"
    _err="/tmp/shellguard_tg_err.$$"
    _code="/tmp/shellguard_tg_code.$$"

    vlog "API ${_method} -> ${_base}"
    vlog "curl args: $*"

    _rc=0
    if [ "$VERBOSE" = "1" ]; then
        curl -s --max-time 15 -w '%{http_code}' -o "$_out" "$@" "$_base" >"$_code" 2>"$_err" || _rc=$?
    else
        curl -s --max-time 15 -w '%{http_code}' -o "$_out" "$@" "$_base" >"$_code" 2>"$_err" || _rc=$?
    fi

    TG_HTTP_CODE=$(cat "$_code" 2>/dev/null || echo "?")
    TG_BODY=$(cat "$_out" 2>/dev/null || true)
    TG_CURL_RC=$_rc
    TG_CURL_ERR=$(cat "$_err" 2>/dev/null || true)

    rm -f "$_out" "$_err" "$_code"

    vlog "curl exit=${TG_CURL_RC} http=${TG_HTTP_CODE}"
    [ -n "$TG_CURL_ERR" ] && vlog "curl stderr: ${TG_CURL_ERR}"
    vlog "response body: ${TG_BODY:-<empty>}"
}

test_telegram_getme() {
    echo "Checking bot token (getMe) ..."
    telegram_api getMe
    if [ "$TG_CURL_RC" != "0" ]; then
        echo "getMe failed: curl exit ${TG_CURL_RC}" >&2
        [ -n "$TG_CURL_ERR" ] && echo "  curl: ${TG_CURL_ERR}" >&2
        return 1
    fi
    if printf '%s' "$TG_BODY" | grep -q '"ok"[[:space:]]*:[[:space:]]*true'; then
        _user=$(printf '%s' "$TG_BODY" | grep -o '"username":"[^"]*"' | head -1 | sed 's/"username":"//;s/"$//')
        echo "Bot OK: @${_user:-unknown}"
        return 0
    fi
    _err=$(printf '%s' "$TG_BODY" | grep -o '"description":"[^"]*"' | head -1 | sed 's/"description":"//;s/"$//')
    echo "getMe failed: ${_err:-unknown error}" >&2
    echo "  response: ${TG_BODY:-<empty>}" >&2
    return 1
}

test_telegram() {
    _host=$(hostname 2>/dev/null || echo "shellguard")
    _msg="[ShellGuard] Test alert from ${_host}
If you see this, Telegram is configured correctly."

    test_telegram_getme || exit 1

    echo "Sending test message to Telegram ..."
    if [ -n "${SHELLGUARD_TG_TOPIC:-}" ]; then
        telegram_api sendMessage \
            --data-urlencode "chat_id=${SHELLGUARD_TG_CHAT}" \
            --data-urlencode "text=${_msg}" \
            --data-urlencode "message_thread_id=${SHELLGUARD_TG_TOPIC}"
    else
        telegram_api sendMessage \
            --data-urlencode "chat_id=${SHELLGUARD_TG_CHAT}" \
            --data-urlencode "text=${_msg}"
    fi

    if [ "$TG_CURL_RC" != "0" ]; then
        echo "sendMessage failed: curl exit ${TG_CURL_RC}" >&2
        [ -n "$TG_CURL_ERR" ] && echo "  curl: ${TG_CURL_ERR}" >&2
        echo "  Check DNS/HTTPS to api.telegram.org from this host." >&2
        exit 1
    fi

    if printf '%s' "$TG_BODY" | grep -q '"ok"[[:space:]]*:[[:space:]]*true'; then
        echo "Telegram test OK (HTTP ${TG_HTTP_CODE})."
        return 0
    fi

    _err=$(printf '%s' "$TG_BODY" | grep -o '"description":"[^"]*"' | head -1 | sed 's/"description":"//;s/"$//')
    echo "Telegram sendMessage failed (HTTP ${TG_HTTP_CODE})." >&2
    [ -n "$_err" ] && echo "  Telegram says: ${_err}" >&2
    echo "  Full response: ${TG_BODY:-<empty>}" >&2
    echo "" >&2
    echo "Common fixes:" >&2
    echo "  - Bot must be admin in the channel/group" >&2
    echo "  - chat_id must match the chat (negative for supergroups/channels)" >&2
    echo "  - topic_id must exist if the group has Topics enabled" >&2
    echo "  - Re-run with: shellguard-configure --verbose --test-only" >&2
    exit 1
}

setup_synology_service() {
    [ -f "$RC_SRC" ] || return 0
    mkdir -p "$(dirname "$RC_DST")"
    cp "$RC_SRC" "$RC_DST"
    chmod 755 "$RC_DST"
    echo "Installed boot script: $RC_DST"
}

start_service() {
    if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
        systemctl daemon-reload 2>/dev/null || true
        systemctl enable shellguard.service 2>/dev/null || true
        systemctl restart shellguard.service
        systemctl --no-pager status shellguard.service || true
        return
    fi

    if is_synology || [ ! -x /usr/bin/systemctl ]; then
        setup_synology_service
        if [ -x "$RC_DST" ]; then
            "$RC_DST" restart
            "$RC_DST" status || true
        else
            echo "Start manually: /usr/bin/shellguard -c $CONF &"
        fi
        return
    fi

    echo "Start manually: /usr/bin/shellguard -c $CONF &"
}

require_root

if [ ! -f "$CONF_EXAMPLE" ] && [ ! -f /usr/bin/shellguard ]; then
    echo "ShellGuard is not installed. Run scripts/install-synology.sh first." >&2
    exit 1
fi

prompt_telegram

if [ "$TEST_ONLY" = "1" ]; then
    test_telegram
    exit 0
fi

write_config
test_telegram

if [ "$DO_START" = "1" ]; then
    start_service
    echo ""
    echo "ShellGuard is running. Open a new shell to trigger an alert."
    echo "Logs: tail -f /var/log/shellguard.log"
    echo "Reconfigure anytime: shellguard-configure --verbose --start"
fi
